# Generated by Django 2.1.4 on 2018-12-30 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marks',
            name='name',
            field=models.ManyToManyField(blank=True, related_name='name', to='login.Students'),
        ),
    ]
