# Generated by Django 2.1.4 on 2018-12-30 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_marks_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marks',
            name='name',
        ),
        migrations.AddField(
            model_name='marks',
            name='name',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='name', to='login.Students'),
            preserve_default=False,
        ),
    ]
